package com.cropcenter;

import android.graphics.Bitmap;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.util.Log;
import android.widget.Toast;

import com.cropcenter.crop.CropExporter;
import com.cropcenter.crop.ExportResult;
import com.cropcenter.metadata.ExifPatcher;
import com.cropcenter.model.CropState;
import com.cropcenter.model.Format;
import com.cropcenter.util.BitmapUtils;
import com.cropcenter.util.SafFileHelper;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.function.Consumer;

/**
 * Encode → write → verify → report pipeline used by SaveController for plain saves and by ReplaceStrategy for the
 * write-first-then-swap flow. Busy-gates, spawns the background worker, and reports success/failure toasts. Knows
 * nothing about collision handling or SAF picker routing — that lives in SaveController / ReplaceStrategy.
 */
final class ExportPipeline
{
	/**
	 * Result of phase 2. exception is non-null when openOutputStream / write / close threw; writeReturned is true
	 * when close() succeeded (close-after-write is the final barrier between "written" and "thrown"). directPath
	 * is non-null when phase 2 took the direct java.io.FileOutputStream branch — set so verifyPhase can confirm
	 * the write via the resolved filesystem path instead of querying SAF provider metadata that may not have
	 * flushed yet: a direct write that bypassed the provider would otherwise verify against a stale
	 * provider-cached SIZE / cached input stream, false-failing a correct write and then deleting it.
	 * Field order follows CLAUDE.md's uppercase-type-before-primitive rule (Exception < File alphabetically).
	 */
	private record WriteOutcome(Exception exception, File directPath, boolean writeReturned)
	{
	}

	private static final String TAG = "ExportPipeline";

	private final SafFileHelper safFiles;
	private final SaveHost host;

	ExportPipeline(SaveHost host, SafFileHelper safFiles)
	{
		this.host = host;
		this.safFiles = safFiles;
	}

	/**
	 * Decide whether the current save is a no-op transformation that lets us write
	 * `state.originalFileBytes` verbatim instead of canvas-encoding. Conditions:
	 *   - Output format is JPEG (PNG has its own encode path; can't bypass).
	 *   - Source format is JPEG (can't bypass-encode a PNG source as JPEG).
	 *   - The image is NOT a graft. Graft saves need a fresh gain map regenerated by
	 *     UltraHdrCompat — the splice ships source's gain map verbatim over the edit's
	 *     primary scan, which is fine for view-only HDR but breaks when the user crops
	 *     (the gain map's spatial alignment shifts off the features it boosts). Forcing
	 *     graft saves through the full encode regenerates the gain map from the spliced
	 *     primary, keeping save-without-crop and save-after-crop both correct.
	 *   - No rotation applied.
	 *   - No grid bake-in.
	 *   - Source bytes available.
	 *   - Crop is either uninitialised (state.hasCenter() == false) OR is the trivial
	 *     full-image crop (cropW/cropH match the source bitmap dimensions). The full-
	 *     image case matters because applying a graft auto-initialises a centered crop
	 *     during applyStateToUi → ensureCropCenter, even though the user has applied no
	 *     real edit. Without the full-image carve-out, every graft save would fall into
	 *     the canvas-encode path even when the user never touched the crop tool.
	 *     (Now defensive — the graft-applied check above already excludes that case.)
	 *
	 * If all hold, the canvas-encoded primary would be a re-encoded near-copy of state.originalFileBytes — close to
	 * byte-identical but with different DCT/Huffman tables and a regenerated EXIF thumbnail. Writing the source
	 * bytes verbatim preserves structure exactly.
	 */
	static boolean canBypassEncode(CropState state, boolean isPng)
	{
		if (isPng)
		{
			return false;
		}
		if (state.getSourceFormat() != Format.JPEG)
		{
			return false;
		}
		if (state.isGraftApplied())
		{
			return false;
		}
		// Honor the same epsilon the renderer uses — sub-epsilon rotation is a no-op there, so forcing a
		// re-encode for it would burn cycles + add quantization noise to a visually identical primary. The
		// ruler caps its finest snap step at this same epsilon so it can never produce a rotation we'd treat as
		// "real" while CropEngine / ViewportMath / BitmapUtils.drawCropped collapse it to zero.
		if (Math.abs(state.getRotationDegrees()) >= BitmapUtils.ROTATION_EPSILON)
		{
			return false;
		}
		if (state.getGridConfig().includeInExport())
		{
			return false;
		}
		if (state.getOriginalFileBytes() == null)
		{
			return false;
		}
		if (state.hasCenter())
		{
			Bitmap src = state.getSourceImage();
			if (src == null)
			{
				return false;
			}
			if (state.getCropW() != src.getWidth() || state.getCropH() != src.getHeight())
			{
				return false;
			}
		}
		// Round-36 user-reported bug: when the source carries no IFD1 thumbnail (screenshots,
		// generated images, files re-encoded by minimal tools that strip metadata), bypass would
		// write the source bytes verbatim — preserving the empty-IFD1 state and never giving the
		// re-encode path's `buildEmbeddedThumbnail` / `ExifPatcher.patch` synthesise chain a chance
		// to add a fresh thumbnail. Force the re-encode path so the saved file gains the embedded
		// preview the user expects. The re-encode trade-off (different DCT/Huffman tables vs
		// source) is worth it for the thumbnail; verbatim fidelity stays preserved for the common
		// case where the source DOES have a pre-computed thumbnail to round-trip.
		if (!ExifPatcher.hasIfd1Thumbnail(state.getJpegMeta()))
		{
			return false;
		}
		return true;
	}

	void exportTo(Uri uri)
	{
		// Default: caller is confident the URI is a fresh document (plain Save As, case C user-renamed, case B
		// Keep). Cleanup a partial write on failure by deleting the URI.
		exportTo(uri, null, false, null);
	}

	/**
	 * Encode-and-write on a background thread.
	 *
	 * `onSavedBg` (optional): runs after the write verifies. The callback receives the exact bytes written so the
	 * Replace flow can drop them onto the target file without re-reading the placeholder (FUSE/MediaStore caching
	 * makes that read unreliable). When onSavedBg is present, doExport's "Saved" toast is suppressed — the callback
	 * issues its own final-outcome message (success or failure dialog).
	 */
	void exportTo(Uri uri, Consumer<byte[]> onSavedBg)
	{
		// Replace flow: the placeholder URI is known-fresh (auto-rename or programmatic createDocument) so
		// delete-on-failure is the correct cleanup. If a future caller needs preserveOnFailure + onSavedBg
		// together, add another overload.
		exportTo(uri, onSavedBg, false, null);
	}

	/**
	 * Overwrite fallback for SaveController case A when the target is a confirmed existing file (priorSize > 0) AND
	 * sibling placeholder creation wasn't available (opaque-ID provider). Direct-writes to `uri` with
	 * preserveOnFailure=true so a verification failure doesn't destroy the original. `replacedName` is used for the
	 * success toast ("Replaced <name>") so the user gets overwrite-specific confirmation that matches what this
	 * path actually did — a generic "Saved N KB" would misrepresent a confirmed overwrite. Not as crash-safe as
	 * Replace's write-then-swap — the destructive write is unavoidable on a provider that won't give us a sibling
	 * placeholder.
	 */
	void exportToOverwrite(Uri uri, String replacedName)
	{
		exportTo(uri, null, true, replacedName);
	}

	/**
	 * Variant for the narrow fallback path in SaveController case A where the provider returned an
	 * ACTION_CREATE_DOCUMENT URI that might point at an existing file and we couldn't create a sibling placeholder
	 * to route through the crash-safe Replace flow. Verification failure MUST NOT delete the URI — it could destroy
	 * the user's original. The residual cost is a partial-write file left on disk when the URI was actually a fresh
	 * document on a provider that doesn't support createDocument; acceptable since both intersections (opaque-ID
	 * provider + fresh-doc create + verify failure) are rare.
	 */
	void exportToPreserving(Uri uri)
	{
		exportTo(uri, null, true, null);
	}

	/**
	 * Export pipeline: encode → write → verify → report.
	 *
	 * Success signal hierarchy (matched by verifyPhase):
	 *   1. Direct file I/O branch (`WriteOutcome.directPath != null`, writeReturned=true) — kernel-level
	 *      `File.length()` matches payload length. The fsync-before-close in `writePhase` /
	 *      `tryDirectAtomicWrite` commits the inode, so length is ground truth.
	 *   2. SAF stream branch, clean write — query `OpenableColumns.SIZE` via SafFileHelper. When the
	 *      query returns the payload length, trust it. When it returns a different value or fails
	 *      (provider omits SIZE), fall through to content readback.
	 *   3. SAF stream branch, threw on close — many SAF providers throw harmless EPIPE / IOException
	 *      on close yet persist the full payload, so route through byte-by-byte content readback
	 *      (`SafFileHelper.readbackByteCount`) as the ground truth.
	 *   4. None of the above → genuine failure; reportFailure deletes the partial file unless
	 *      preserveOnFailure is set.
	 * Returns the exact bytes written when the file on disk is verified to hold the full payload,
	 * or null on failure. Callers that need to run a post-write step (e.g. Replace's File-I/O
	 * swap) use the returned bytes so they don't have to re-read the placeholder from the
	 * filesystem — that read can go through FUSE/MediaStore layers that aren't necessarily in
	 * sync with the SAF write we just did. The contract is "verified by size + readback", not
	 * "definitively saved" — the latter would falsely imply the kernel cache has flushed.
	 *
	 * `isReplaceSave` — true when this export is the placeholder write of a Replace flow. Suppresses doExport's
	 * "Saved" toast because the Replace swap that follows fires its own outcome message.
	 *
	 * `preserveOnFailure` — when verifyPhase rejects the write, true leaves the partial file on disk; false deletes
	 * it. Set by the caller based on whether the URI might point at user data (e.g. SaveController's case-A
	 * fallback when we can't determine the URI is a fresh doc) vs. being a known-fresh placeholder (Replace flow,
	 * plain Save As, etc.).
	 *
	 * `replacedName` — when non-null AND isReplaceSave is false, a successful save emits "Replaced <replacedName>"
	 * instead of the generic "Saved N KB" toast. Used by the opaque-ID overwrite-fallback path (exportToOverwrite)
	 * so a confirmed overwrite announces itself as an overwrite. Null for plain Save As and the fallback
	 * preservation path.
	 *
	 * Failure toasts fire regardless of the flags.
	 */
	private byte[] doExport(Uri uri, boolean isReplaceSave, boolean preserveOnFailure, String replacedName)
	{
		boolean isPng = host.getState().getExportConfig().format() == Format.PNG;
		boolean srcHadHdr = host.getState().getGainMap() != null && host.getState().getGainMap().length > 0;

		ExportResult encoded = encodePhase(isPng, srcHadHdr);
		if (encoded == null)
		{
			return null;
		}
		byte[] data = encoded.bytes();
		WriteOutcome write = writePhase(uri, data, preserveOnFailure);
		if (!verifyPhase(uri, data, write))
		{
			reportFailure(uri, write.exception(), preserveOnFailure);
			return null;
		}
		if (!isReplaceSave)
		{
			if (replacedName != null)
			{
				reportReplaced(replacedName);
			}
			else
			{
				reportSuccess(data, srcHadHdr, isPng, encoded.hdrAttached());
			}
		}
		return data;
	}

	/**
	 * Phase 1 — encode. Runs CropExporter on the current state and returns the JPEG / PNG bytes, or null when
	 * encoding failed (in which case a failure toast is already queued).
	 *
	 * Bypass: when the user has applied no transformations (no crop, no rotation, no grid bake-in, JPEG-to-JPEG
	 * round-trip on a NON-graft source), write `state.originalFileBytes` verbatim instead of canvas-encoding. This
	 * preserves byte-perfect fidelity for re-saves of an unedited file. The bypass is explicitly disabled for
	 * grafts (canBypassEncode rejects state.isGraftApplied) — graft saves need the canvas re-encode to regenerate
	 * the gain map from the spliced primary, so the HDR boost stays spatially aligned with the edit's pixels.
	 * Skipping that for a graft would ship source's gain map verbatim over the spliced primary and visibly
	 * mis-place the boost wherever the edit changed pixels.
	 */
	private ExportResult encodePhase(boolean isPng, boolean srcHadHdr)
	{
		try
		{
			if (canBypassEncode(host.getState(), isPng))
			{
				byte[] data = host.getState().getOriginalFileBytes();
				Log.d(TAG, "Bypassed encode (no transforms applied) — " + data.length + " bytes");
				// Bypass writes original bytes verbatim, including the gain map when source was HDR.
				// canBypassEncode rejects grafts and any transform that would invalidate gain-map
				// alignment, so srcHadHdr accurately reflects what the bypassed bytes carry.
				return new ExportResult(data, srcHadHdr);
			}
			ExportResult result = CropExporter.export(host.getState(), host.getActivity().getCacheDir());
			Log.d(TAG, "Encoded " + result.bytes().length + " bytes (srcHdr=" + srcHadHdr
				+ " isPng=" + isPng + " hdrAttached=" + result.hdrAttached() + ")");
			return result;
		}
		catch (Exception | OutOfMemoryError e)
		{
			// Widened to OOM as well as Exception so a primary-bitmap or HDR-render allocation failure on
			// a multi-MP source still surfaces a user-facing "Export failed" toast — without OOM in the
			// catch, runExportBg's finally would hide the progress overlay while the worker died with an
			// uncaught Error, leaving the user staring at an unresponsive editor with no feedback.
			// Mirrors the load path's OOM handling and CropExporter.generateThumbnail's catch widening.
			Log.e(TAG, "Encode failed", e);
			final String emsg = "Export failed: " + e.getMessage();
			host.runOnUiThread(() -> host.toastIfAlive(emsg, Toast.LENGTH_SHORT));
			return null;
		}
	}

	private void exportTo(Uri uri, Consumer<byte[]> onSavedBg, boolean preserveOnFailure, String replacedName)
	{
		if (host.getState().getSourceImage() == null)
		{
			return;
		}
		if (!host.getBusy().compareAndSet(false, true))
		{
			host.showBusyToast();
			return;
		}
		// Between the busy acquire and the runInBackground enqueue, any throw from the UI setup (setBusyUi /
		// showProgress can hit findViewById / setText during an unusual view-tree state) OR from the executor
		// itself (RejectedExecutionException after onDestroy shutdown racing a save tap) would otherwise strand
		// busy=true forever — the background finally never runs because the Runnable was never submitted. Clear
		// busy + hide UI before propagating so a second Save tap isn't permanently rejected with "Busy — try
		// again". runInBackground sits inside the same try so an executor-level reject gets the same cleanup as
		// a view-tree throw — matches ImageLoadController.load and GraftController.onEditPicked.
		boolean isReplaceSave = onSavedBg != null;
		try
		{
			host.setBusyUi(true);
			host.showProgress("Saving…");
			host.runInBackground(() ->
				runExportBg(uri, isReplaceSave, preserveOnFailure, replacedName, onSavedBg));
		}
		catch (RuntimeException e)
		{
			Log.w(TAG, "pre-enqueue UI/dispatch threw; releasing busy flag", e);
			host.getBusy().set(false);
			host.setBusyUi(false);
			host.hideProgress();
			throw e;
		}
	}

	/**
	 * Phase 4 — failure report. Toasts the exception message when available; deletes the partially-written SAF doc
	 * so a failed save doesn't leave a truncated file behind — but ONLY when `preserveOnFailure` is false. When the
	 * URI pointed at an existing file before the write (provider-confirmed overwrite), deletion would turn the
	 * verification failure into data loss of the user's original; we leave the (now partial) file on disk and rely
	 * on the failure toast so the user knows to re-save. Partial-write corruption stays preferable to outright
	 * deletion of a file the user didn't explicitly tell us to destroy.
	 */
	private void reportFailure(Uri uri, Exception writeException, boolean preserveOnFailure)
	{
		final String emsg = writeException != null
			? "Export failed: " + writeException.getMessage()
			: "Export failed";
		host.runOnUiThread(() -> host.toastIfAlive(emsg, Toast.LENGTH_SHORT));
		if (preserveOnFailure)
		{
			Log.w(TAG, "preserving " + uri + " on failure (had prior content)");
			return;
		}
		safFiles.tryDeleteSafDocument(uri);
	}

	/**
	 * Phase 4 — overwrite-specific success report. Fires "Replaced <name>" when the caller is the opaque-ID
	 * overwrite-fallback path that direct-wrote to the target with preserve-on-failure (a real overwrite, not a
	 * fresh save), and deserves a matching user message. The full Replace flow (with placeholder + swap) does not
	 * use this path — its success toast is fired by ReplaceStrategy after verifyReplace confirms the final state.
	 */
	private void reportReplaced(String name)
	{
		final String msg = "Replaced " + name;
		host.runOnUiThread(() -> host.toastIfAlive(msg, Toast.LENGTH_SHORT));
	}

	/**
	 * Phase 4 — success report. "Saved NKB [HDR OK]" / "[HDR dropped]" on a save that dropped an HDR source (only
	 * for JPEG — PNG can't carry gain maps, which is a format limitation, not a failure, so the suffix is
	 * suppressed).
	 *
	 * `hdrAttached` is the structural answer threaded back through ExportResult — true when the encode
	 * actually appended the Ultra HDR gain map, false on the HDR-drop path (gain-map render failed, MPF
	 * patch rejected, etc.) and on the bypass path when srcHadHdr is false. Replaces an earlier full-file
	 * substring scan for "hdrgm" that false-positive'd on preserved trailers, stale metadata, and
	 * Extended-XMP segments.
	 *
	 * @param data         encoded output bytes (used for the size component of the toast)
	 * @param srcHadHdr    true when the source carried a gain map (gates whether to show any HDR suffix)
	 * @param isPng        true for PNG output (no HDR suffix regardless — PNG can't carry gain maps)
	 * @param hdrAttached  true when the output actually carries the Ultra HDR gain map (drives [HDR OK]
	 *                     vs [HDR dropped])
	 */
	private void reportSuccess(byte[] data, boolean srcHadHdr, boolean isPng, boolean hdrAttached)
	{
		String hdrSuffix;
		if (!srcHadHdr || isPng)
		{
			hdrSuffix = "";
		}
		else if (hdrAttached)
		{
			hdrSuffix = " [HDR OK]";
		}
		else
		{
			hdrSuffix = " [HDR dropped]";
		}
		final String msg = "Saved " + data.length / 1024 + "KB" + hdrSuffix;
		host.runOnUiThread(() -> host.toastIfAlive(msg, Toast.LENGTH_SHORT));
	}

	/**
	 * Background-thread body of exportTo: runs the encode/write/verify pipeline, fires the optional onSavedBg
	 * callback when the write verifies, and releases the busy flag in finally so a thrown callback doesn't strand
	 * Save / Open behind a permanent "Busy" toast.
	 *
	 * The replace callback owns its own success/failure messaging, so doExport suppresses the "Saved" toast when
	 * onSavedBg is set. If the callback itself throws before firing its outcome message, that suppression would
	 * otherwise leave the user with no feedback at all (silent save). Catch + log + post a generic failure toast so
	 * the user knows something went wrong; the exception detail is in the log.
	 *
	 * @param uri               SAF URI to write to
	 * @param isReplaceSave     true when this export is the placeholder write of a Replace flow
	 * @param preserveOnFailure when verifyPhase rejects the write, true leaves the partial file on disk
	 * @param replacedName      when non-null AND isReplaceSave is false, success emits "Replaced <name>"
	 * @param onSavedBg         optional post-write callback invoked with the verified bytes; null for plain saves
	 */
	private void runExportBg(Uri uri, boolean isReplaceSave, boolean preserveOnFailure, String replacedName,
		Consumer<byte[]> onSavedBg)
	{
		try
		{
			byte[] data = doExport(uri, isReplaceSave, preserveOnFailure, replacedName);
			if (data != null && onSavedBg != null)
			{
				try
				{
					onSavedBg.accept(data);
				}
				catch (Exception e)
				{
					Log.w(TAG, "post-save step threw", e);
					host.runOnUiThread(() -> host.toastIfAlive(
						"Save step failed — check log", Toast.LENGTH_LONG));
				}
			}
		}
		finally
		{
			host.getBusy().set(false);
			host.runOnUiThread(() -> host.setBusyUi(false));
			host.hideProgress();
		}
	}

	/**
	 * Direct file I/O via a temp sibling + fsync + atomic rename. Used when the caller flagged
	 * `preserveOnFailure=true` — the target URI may already contain user data, so opening it in truncate
	 * mode is unsafe (a disk-full / I/O error between open and full-write would leave the original
	 * zeroed). Writes the payload to `.<name>.cropcenter-tmp-<nanos>` in the same parent directory, fsyncs,
	 * confirms byte count, and atomic-moves the temp onto the target via Files.move with
	 * ATOMIC_MOVE + REPLACE_EXISTING. Mirrors the proven pattern in ReplaceStrategy.replaceViaFileIo and
	 * keeps the target file content intact on any pre-move failure.
	 *
	 * Returns the WriteOutcome on success, or null when any step failed. Caller's fall-through behavior
	 * depends on the preserveOnFailure mode: when preserveOnFailure=true, writePhase converts a null
	 * return into a synthetic failed WriteOutcome rather than falling through to the SAF stream path —
	 * SAF "w" truncation behavior is provider-dependent (some truncate at open time), so a mid-stream
	 * failure after fall-through could zero the user's original. Surfaces as a clean "Export failed"
	 * toast with the target intact. When preserveOnFailure=false, this method isn't called at all —
	 * writePhase takes the simpler truncate-mode direct write since the URI is a known-fresh
	 * placeholder (Replace flow, plain Save As).
	 */
	private WriteOutcome tryDirectAtomicWrite(File target, byte[] data)
	{
		File parent = target.getParentFile();
		if (parent == null)
		{
			return null;
		}
		File tempFile = new File(parent,
			"." + target.getName() + ".cropcenter-tmp-" + System.nanoTime());
		try (FileOutputStream fos = new FileOutputStream(tempFile))
		{
			fos.write(data);
			fos.getFD().sync();
		}
		catch (Exception e)
		{
			Log.w(TAG, "Atomic write temp " + tempFile + " failed; target preserved: " + e.getMessage());
			if (tempFile.exists() && !tempFile.delete())
			{
				Log.w(TAG, "couldn't clean up temp file " + tempFile);
			}
			return null;
		}
		long written = tempFile.length();
		if (written != data.length)
		{
			Log.w(TAG, "Atomic write temp produced " + written + " bytes; expected " + data.length);
			if (!tempFile.delete())
			{
				Log.w(TAG, "couldn't clean up short temp file " + tempFile);
			}
			return null;
		}
		try
		{
			Files.move(tempFile.toPath(), target.toPath(),
				StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
		}
		catch (Exception e)
		{
			Log.w(TAG, "Atomic swap " + tempFile + " → " + target + " failed; target preserved: "
				+ e.getMessage());
			if (tempFile.exists() && !tempFile.delete())
			{
				Log.w(TAG, "couldn't clean up temp file " + tempFile);
			}
			return null;
		}
		Log.d(TAG, "Atomic direct write delivered " + data.length + " bytes to " + target);
		if (!target.setLastModified(System.currentTimeMillis()))
		{
			Log.w(TAG, "setLastModified failed on " + target);
		}
		MediaScannerConnection.scanFile(host.getActivity().getApplicationContext(),
			new String[] { target.getAbsolutePath() }, null, null);
		return new WriteOutcome(null, target, true);
	}

	/**
	 * Phase 3 — verify. Trust a clean write only after a cheap size-query confirms the file
	 * on disk matches the payload length. Some SAF providers don't truncate on "w" mode, so a
	 * write that's shorter than a prior version leaves stale trailing bytes behind — the
	 * write returns cleanly but the file is corrupt. Three fall-through conditions drop to
	 * byte-by-byte content readback:
	 *   - size query disagrees with payload length (likely un-truncated prior version)
	 *   - size query fails / provider doesn't expose SIZE (can't fast-path, must verify)
	 *   - write path threw (many providers throw harmless EPIPE on close yet persist the
	 *     full payload — readback is the ground truth)
	 * Returns true when the save is good, false when it's genuinely lost.
	 *
	 * Direct-file shortcut: when writePhase took the direct
	 * java.io.FileOutputStream + fsync branch, the SAF provider's cached metadata may not have
	 * caught up with the on-disk bytes yet — the MediaScannerConnection.scanFile fired after the
	 * write is asynchronous and almost certainly hasn't reindexed by the time this verify runs.
	 * Querying SIZE through the SAF URI in that window can return the pre-write byte count even
	 * though the bytes ARE on disk, causing verifyPhase to false-fail and reportFailure to then
	 * delete a correctly-written file. Skip the SAF query entirely when directPath is set and
	 * verify via File.length() — the fsync after write guarantees the inode is committed before
	 * we read its length.
	 *
	 * Deliberate trade-off: when the write didn't throw AND SIZE matches the payload length, we
	 * trust the provider and skip content readback. A misbehaving provider that returned success + correct byte
	 * count but stored same-length wrong content would slip through as a false-positive save. We accept this
	 * because: (a) it requires
	 * active provider corruption, not a real-world failure mode for any major SAF / MediaStore /
	 * cloud provider; (b) always-content-verify would double the I/O on every replace save, a
	 * measurable hot-path tax for a hypothetical bug; (c) the readback path IS exercised on every
	 * SIZE-omitted / SIZE-mismatched / write-threw branch, which covers all real provider failure
	 * modes we've seen in the wild.
	 */
	private boolean verifyPhase(Uri uri, byte[] data, WriteOutcome write)
	{
		if (write.directPath() != null && write.writeReturned())
		{
			// Direct file I/O path: fos.getFD().sync() before close committed the bytes to the
			// inode; trust the kernel-level length over the SAF provider's cached metadata.
			long fileLen = write.directPath().length();
			boolean directOk = fileLen == data.length;
			Log.d(TAG, "Direct-path verify: file=" + write.directPath() + " length=" + fileLen
				+ " expected=" + data.length + " → savedOk=" + directOk);
			return directOk;
		}
		boolean savedOk = write.writeReturned();
		long sizeCheck = -1;
		long verifiedBytes = -1;
		if (savedOk)
		{
			sizeCheck = safFiles.querySafFileSize(uri);
			if (sizeCheck < 0)
			{
				Log.d(TAG, "Clean write but provider omits SIZE; verifying content");
				savedOk = false;
			}
			else if (sizeCheck != data.length)
			{
				Log.w(TAG, "Clean write but size " + sizeCheck + " != expected "
					+ data.length + " — provider may not have truncated; verifying content");
				savedOk = false;
			}
		}
		if (!savedOk)
		{
			verifiedBytes = safFiles.readbackByteCount(uri, data);
			savedOk = verifiedBytes == data.length;
			if (savedOk)
			{
				Log.d(TAG, "Recovered via content-verified readback: " + verifiedBytes + " bytes");
			}
		}
		Log.d(TAG, "Save result: writeReturned=" + write.writeReturned()
			+ " sizeCheck=" + sizeCheck + " verifiedBytes=" + verifiedBytes
			+ " expected=" + data.length + " → savedOk=" + savedOk);
		return savedOk;
	}

	/**
	 * Phase 2 — write. Tries direct java.io.FileOutputStream first when the URI resolves to a real filesystem
	 * path via SafFileHelper.fileFromSafUri (typically requires MANAGE_EXTERNAL_STORAGE) — bypasses the SAF
	 * stream path entirely. On Samsung devices the SAF stream path has been observed to silently corrupt
	 * writes: openOutputStream("w") returns success and reports the correct post-write byte count, but the
	 * actual disk content never changes. The provider buffers the write in memory and never flushes,
	 * leaving the placeholder document with stale bytes that downstream Replace strategies then propagate
	 * onto the target (observed in user repros: byte-identical re-exports via Replace persisted across a
	 * clean rebuild that should have shifted the gainmap encoding). Direct file I/O sidesteps the entire
	 * SAF write path: bytes land via the kernel filesystem layer where the provider's caching can't
	 * intercept. The fsync after write forces durability before close. Trailing MediaScannerConnection.scanFile
	 * triggers MediaStore reindex so Gallery / Photos sees the new content (without it, the on-disk file is
	 * correct but every MediaStore consumer keeps showing the pre-write thumbnail).
	 *
	 * Two direct-write modes:
	 *   - preserveOnFailure=true (exportToOverwrite, exportToPreserving): the URI may already contain user
	 *     data. Routes through tryDirectAtomicWrite — temp sibling + fsync + atomic rename — so a mid-write
	 *     failure leaves the original intact. Without this, FileOutputStream(target) truncated the target
	 *     at open time and a disk-full error after open would zero the user's original.
	 *   - preserveOnFailure=false (Replace placeholder, Save As to a known-fresh document): truncate-mode
	 *     direct write is safe because the destination has no prior data to lose; uses the simpler
	 *     FileOutputStream path that doesn't need a sibling write + rename round-trip.
	 *
	 * Falls back to SAF stream when fileFromSafUri returns null (cloud / opaque-ID providers, or
	 * non-primary volumes the helper can't resolve) — those paths don't exhibit the silent corruption
	 * pattern because they're not Samsung MediaStore.
	 *
	 * Uses try-with-resources so close() runs after writeReturned=true and a close-only failure can't
	 * invalidate a successful write. Returns the outcome so phase 3 can decide whether to trust it or fall
	 * through to a readback.
	 */
	private WriteOutcome writePhase(Uri uri, byte[] data, boolean preserveOnFailure)
	{
		File directPath = safFiles.fileFromSafUri(uri);
		if (directPath != null)
		{
			if (preserveOnFailure)
			{
				WriteOutcome atomic = tryDirectAtomicWrite(directPath, data);
				if (atomic != null)
				{
					return atomic;
				}
				// Atomic path failed AND preserveOnFailure is true — surface as a clean save failure
				// rather than falling through to openOutputStream("w") on the SAME possibly-existing
				// target. SAF "w" truncation behavior is provider-dependent: some providers truncate
				// the file at open time, so a write that fails mid-stream after the truncate-on-open
				// leaves the user's original zeroed or partially overwritten. That defeats the whole
				// point of taking the preserveOnFailure branch — the caller (exportToOverwrite /
				// exportToPreserving) flagged the URI as possibly containing user data we don't want
				// to destroy. Synthesizing a writeException + writeReturned=false routes through
				// verifyPhase's failure path, which calls reportFailure with preserveOnFailure=true
				// (per doExport's argument-passing), so the target on disk stays intact.
				return new WriteOutcome(new IOException(
					"Atomic direct-write to " + directPath + " failed; refusing to fall through to "
						+ "SAF truncate-mode write on preserveOnFailure=true target"),
					null, false);
			}
			else
			{
				try (FileOutputStream fos = new FileOutputStream(directPath))
				{
					fos.write(data);
					fos.getFD().sync();
					Log.d(TAG, "Direct file I/O wrote " + data.length + " bytes to " + directPath);
					// Force mtime update even when the new bytes match the old bytes. Samsung's
					// FUSE-backed scoped storage skips mtime refresh on content-identical writes
					// (likely dedup at the FUSE layer) — userspace observers see the old mtime,
					// creating ambiguity about whether the save actually ran. setLastModified after
					// the write + sync forces the timestamp regardless of dedup behaviour, so the
					// user always has a concrete signal that the save landed — deterministic
					// encode of identical inputs produces identical bytes, but mtime should still
					// reflect the save.
					if (!directPath.setLastModified(System.currentTimeMillis()))
					{
						Log.w(TAG, "setLastModified failed on " + directPath);
					}
					// Trigger MediaStore reindex so the new content surfaces in gallery apps. Use
					// the application context so a config-change race during the scan doesn't keep
					// a destroyed Activity alive (mirrors ReplaceStrategy.replaceViaFileIo's
					// pattern).
					MediaScannerConnection.scanFile(host.getActivity().getApplicationContext(),
						new String[] { directPath.getAbsolutePath() }, null, null);
					return new WriteOutcome(null, directPath, true);
				}
				catch (Exception e)
				{
					Log.w(TAG, "Direct file I/O failed; falling through to SAF stream: "
						+ e.getMessage());
				}
			}
		}
		boolean writeReturned = false;
		Exception writeException = null;
		try (OutputStream os = host.getActivity().getContentResolver().openOutputStream(uri, "w"))
		{
			if (os == null)
			{
				throw new IOException("openOutputStream returned null");
			}
			os.write(data);
			writeReturned = true;
		}
		catch (Exception e)
		{
			writeException = e;
			Log.w(TAG, "Write path threw (may still have persisted)", e);
		}
		return new WriteOutcome(writeException, null, writeReturned);
	}
}
